apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  # Change these to match what your Node.js app expects!
  MYSQL_ROOT_PASSWORD: "netflix_password123"
  MYSQL_DATABASE: "netflix_db"